### PR TITLE
Bika LIMS JSON API v2

### PR DESCRIPTION
**Pull request by ramonski**
## Description of the issue/feature this PR addresses

Please see https://github.com/bikalabs/bika.lims/issues/2013 for details

The new RESTful Bika LIMS API has the following super-powers under the hood:

- Supports JSON and XML output via `?asxml=True`
- Lists all Bika LIMS content types via HTTP GET on `<base-url>/@@API/v2/<portal-type>`
- Create/Update/Delete (deactivate) via HTTP POST on `<base-url>/@@API/v2/{create,update,delete}/<uid>`
-  Search for Contents via HTTP GET on `<base-url>/@@API/v2/search`
-  User listing via HTTP GET on `<base-url>/@@API/v2/users`
- Login via HTTP GET on `<base-url>/@@API/v2/login?__ac_name=<name>&__ac_password=<pass>`
- Logout via HTTP GET on `<base-url>/@@API/v2/logout`
- It supports all catalog indexes as request parameters, e.g. `<base-url>/@@API/v2/search?portal_type=Instrument&title=CropScan`
- It supports variable batching through the `?limit` request parameter
- Knows how to handle references
- Built to be extended through the ZCA, e.g. `IDataManager` allows to `set` and `get` field values,  `IDataProvider` extracts information of contents,  `ICatalog` searches one/multiple catalogs, `ICatalogQuery` knows how to `make_query`

Most of the Docs from http://plonejsonapiroutes.readthedocs.io/en/latest/ can be used for reference.

--
I confirm I have read the [Bika LIMS Developer Guidelines][1] and that I have
tested the PR thoroughly and coded it according to [PEP8][2] standards.

[1]: https://github.com/bikalabs/bika.lims/wiki/Bika-LIMS-Developer-Guidelines

[2]: https://www.python.org/dev/peps/pep-0008

### CODE REVIEW

**Comment by ramonski** [comment]
Things to do / still open:

- [ ] AR Creation process
- [ ] Fixed container locations for content type creation (e.g. {"Instrument": "bika_setup/bika_instruments"})
- [ ] Mapping of content types which are not allowed/allowed to create through the API. E.g. it would make sense to disallow all `bika_setup` first-level folders, e.g. `InstrumentTypes`, `InstrumentLocations` etc.
- [ ] Copy/Paste functionality
- [ ] Reference handling: At the moment the user passes in a dictionary value for a reference field in the HTTP POST Body, e.g. `{"InstrumentType": {"title": "AA"}}` for Instrument updates on `<base-url>/@@API/v2/instrument/<uid>/update`. The update machinery queries for `{"portal_type": "InstrumentType", "title": "AA"}` and (if found) updates the field with the new reference object. Does this make sense or should we update the title of the current reference object??

**Comment by ramonski** [comment]
AR creation works now as well and can handle a HTTP like this:

```json
{
 "parent_path": "/Plone/clients/client-1",
 "Analyses": ["Zinc", "Calcium"],
 "SampleType": "Water",
 "SamplingDate": "2017/04/25",
 "Contact": "/Plone/clients/client-1/contact-2"
}
```

Reference fields support now UIDs, paths, catalog queries as a dictionary, objects and simple value searches. Please check `bika.lims.jsonapi.datamanager.ATDataManager` for further details.

The new proxy fields of ARs are also supported.

**Comment by andersonsmith** [comment]
Are analysis profiles and templates also supported during creation?

**Comment by ramonski** [comment]
Implemented `IFieldManager` for more granular control of fields, e.g. `ReferenceField`, `ProxyField` etc..

Reference fields handle now the following values:

- Single UID or list of UIDS, e.g. `e97178d71fd1494b9cf6d32eb6569cd0` or [`UID1`, `UID2` ...]
- Single content objects or a list of content objects
- Single dictionary query (will be passed to the `api.search`) or a list of dictionaries
- Single physical paths to objects or a list of physical paths, e.g. `/Plone/bika_setup/bika_analysisprofiles/analysisprofile-6` or [`/Plone/bika_setup/bika_analysisprofiles/analysisprofile-3`, `/Plone/bika_setup/bika_analysisprofiles/analysisprofile-4`]


@andersonsmith: You can HTTP POST to `<base-url>/@@API/v2/analysisprofile/create` the following payload to create a new AnalysisProfile:

```json
{
 "title": "My Profile",
 "ProfileKey": "MP",
 "AnalysisProfilePrice": "17.5",
 "AnalysisProfileVAT": "19.0",
 "Service": [
   {"title":"Calcium"},
   {"title":"Magnesium"}
 ],
 "description": "Hardness Profile"
}
```

advanced_rest_client

my_profile_ _bika

**Comment by ramonski** [comment]
Some timings from my machine:

- Creation of a new `AnalysisRequest`: 872.00 ms
- Creation of a new `AnalysisProfile`: 61.00 ms
- Creation of a new `Client`: 129.00 ms
- Creation of a new `Contact`: 131.00 ms

**Comment by ramonski** [comment]
Ok, the creation of 60 ARs at once over the API is a little bit slow and took 47868.00 ms x_X

**Comment by rockfruit** [comment]
one of the most fun to read pull requests of the year.

**Comment by rockfruit** [comment]
I removed not ready (after the fact) because I believe copy/paste is boring in our use-case.

**Pull request merged**
