### PR TITLE
LIMS-2355 Sampling deviations site error listing Active and Dormant Items separately [was: missing review states]

### PR DESCRIPTION
**Pull request by rockfruit**
Removed bad code.
Stupid error from very old code who's purpose I cannot fathom Something to do with the 'ManageBika' permission deciding if a user can view the dormant/active filters, meanwhile, this permission is not used to allow access to the default/all filter.

### CODE REVIEW

**Comment by xispa** [comment]
Same same but different:
https://github.com/bikalabs/bika.lims/blob/5e78bc9df2df9d2197221b8755ecf328e269d17d/bika/lims/browser/pricelist.py#L80
https://github.com/bikalabs/bika.lims/blob/5e78bc9df2df9d2197221b8755ecf328e269d17d/bika/lims/content/methods.py#L89

**Comment by rockfruit** [comment]
Thanks for finding those

**Comment by rockfruit** [comment]
Sorry about the conflicts here?  I merged master into this branch without a hitch, but github still isn't happy.

**Comment by xispa** [comment]
Looks ok to me. Don't worry about the merge, I'll do now.

**Pull request merged**
