### PR TITLE
Add slack.com links to README.rst and bika-frontpage.pt

### PR DESCRIPTION
**Pull request by rockfruit**

### CODE REVIEW

**Comment by chandan5** [comment]
Yaayyy!! This is great :+1: Bika on Slack :)

**Comment by rockfruit** [comment]
The future is now :>

**Comment by chandan5** [comment]
Yip. Is it linked to IRC? Have we completely moved to slack ?

**Comment by rockfruit** [comment]
It's done, but not quite working in both directions yet.  I keep an eye on the IRC channel in the meantime.

**Pull request merged**
