### PR TITLE
LIMS-2449 Thermo iCAP Q results importer

### PR DESCRIPTION
**Pull request by andersonsmith**
## Description of the issue/feature this PR addresses

https://jira.bikalabs.com/browse/LIMS-2449

## Current behavior before PR

No importer available for this instrument/software package.

## Desired behavior after PR is merged

Results importing available.

--
I confirm I have read the [Bika LIMS Developer Guidelines][1] and that I have
tested the PR thoroughly and coded it according to [PEP8][2] standards.

[1]: https://github.com/bikalabs/bika.lims/wiki/Bika-LIMS-Developer-Guidelines

[2]: https://www.python.org/dev/peps/pep-0008

### CODE REVIEW

**Comment by ramonski** [comment]
Hmm, not sure why I can't resolve the conflicting files within GitHub... @andersonsmith did you delete the origin repository?

**Comment by ramonski** [comment]
Hmm, not easy to get this one merged @andersonsmith. I don't see this branch locally on my computer. How did it come to the `unknown repository` of this PR?

**Comment by andersonsmith** [comment]
Good question, I'm not sure.  The changes are straight forward.  Why don't we cancel this PR and I'll resubmit from a fresh fork from master?

**Comment by ramonski** [comment]
@andersonsmith: perfect, let's do it like this, thanks!

**Pull request closed without merging**
